'use client'

import { useState, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { cn } from '@/lib/utils'
import { formatRelativeTime, DOCUMENT_CATEGORY_LABELS, type DocumentCategory, type ProjectRole } from '@laneshare/shared'
import { useToast } from '@/hooks/use-toast'
import {
  FileText,
  Plus,
  Search,
  Layers,
  Code,
  BookOpen,
  Wrench,
  Lightbulb,
  Users,
  MessageSquare,
  ChevronRight,
  ChevronDown,
  Trash2,
  X,
  CheckSquare,
  FolderGit2,
  Bot,
  AlertCircle,
  CheckCircle2,
  Pencil,
} from 'lucide-react'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'

interface DocumentListItem {
  id: string
  project_id: string
  title: string
  slug: string
  category: DocumentCategory
  description?: string
  tags: string[]
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  // Review-related fields for auto-generated docs
  source_repo_id?: string
  source_bundle_id?: string
  source_repo_page_id?: string
  evidence_json?: unknown[]
  original_markdown?: string
  verification_score?: number
  verification_issues?: unknown[]
  needs_review?: boolean
  reviewed?: boolean
  reviewed_at?: string
  reviewed_by?: string
  user_edited?: boolean
  user_edited_at?: string
  creator?: {
    id: string
    email: string
    full_name?: string
    avatar_url?: string
  }
  source_repo?: {
    id: string
    owner: string
    name: string
  }
}

interface DocumentsViewProps {
  projectId: string
  projectName: string
  documents: DocumentListItem[]
  initialCategory?: string
  initialSearch?: string
  initialRepoId?: string
  userRole: ProjectRole
}

const CATEGORY_ICONS: Record<DocumentCategory, React.ElementType> = {
  architecture: Layers,
  api: Code,
  feature_guide: BookOpen,
  runbook: Wrench,
  decision: Lightbulb,
  onboarding: Users,
  meeting_notes: MessageSquare,
  other: FileText,
}

const CATEGORY_COLORS: Record<DocumentCategory, string> = {
  architecture: 'text-purple-600 bg-purple-50 dark:bg-purple-950/30',
  api: 'text-blue-600 bg-blue-50 dark:bg-blue-950/30',
  feature_guide: 'text-green-600 bg-green-50 dark:bg-green-950/30',
  runbook: 'text-orange-600 bg-orange-50 dark:bg-orange-950/30',
  decision: 'text-yellow-600 bg-yellow-50 dark:bg-yellow-950/30',
  onboarding: 'text-pink-600 bg-pink-50 dark:bg-pink-950/30',
  meeting_notes: 'text-gray-600 bg-gray-50 dark:bg-gray-950/30',
  other: 'text-slate-600 bg-slate-50 dark:bg-slate-950/30',
}

type FilterMode = 'all' | 'manual' | 'auto-generated'
type ReviewFilter = 'all' | 'needs-review' | 'reviewed' | 'user-edited'

export function DocumentsView({
  projectId,
  projectName,
  documents,
  initialCategory,
  initialSearch,
  initialRepoId,
  userRole,
}: DocumentsViewProps) {
  const router = useRouter()
  const { toast } = useToast()
  const [search, setSearch] = useState(initialSearch || '')
  const [selectedCategory, setSelectedCategory] = useState<DocumentCategory | null>(
    (initialCategory as DocumentCategory) || null
  )
  const [selectedRepoId, setSelectedRepoId] = useState<string | null>(initialRepoId || null)
  const [filterMode, setFilterMode] = useState<FilterMode>('all')
  const [reviewFilter, setReviewFilter] = useState<ReviewFilter>('all')
  const [expandedRepos, setExpandedRepos] = useState<Set<string>>(new Set(initialRepoId ? [initialRepoId] : []))
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['quick-filters', 'source', 'repositories', 'categories']))

  // Selection mode state
  const [selectionMode, setSelectionMode] = useState(false)
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [isDeleting, setIsDeleting] = useState(false)

  const canDelete = ['OWNER', 'MAINTAINER'].includes(userRole)

  // Separate manual and auto-generated documents
  const manualDocs = useMemo(() => documents.filter((d) => !d.source_repo_id), [documents])
  const autoGeneratedDocs = useMemo(() => documents.filter((d) => !!d.source_repo_id), [documents])

  // Review status counts
  const reviewCounts = useMemo(() => ({
    needsReview: documents.filter((d) => d.needs_review && !d.reviewed).length,
    reviewed: documents.filter((d) => d.reviewed).length,
    userEdited: documents.filter((d) => d.user_edited).length,
  }), [documents])

  // Group auto-generated documents by repo
  const docsByRepo = useMemo(() => {
    return autoGeneratedDocs.reduce((acc, doc) => {
      const repoId = doc.source_repo_id!
      if (!acc[repoId]) {
        acc[repoId] = {
          repo: doc.source_repo!,
          docs: [],
        }
      }
      acc[repoId].docs.push(doc)
      return acc
    }, {} as Record<string, { repo: { id: string; owner: string; name: string }; docs: DocumentListItem[] }>)
  }, [autoGeneratedDocs])

  // Flat list of repos for quick access
  const repoList = useMemo(() => {
    return Object.entries(docsByRepo)
      .map(([repoId, { repo, docs }]) => ({
        id: repoId,
        name: repo.name,
        owner: repo.owner,
        count: docs.length,
        needsReviewCount: docs.filter((d) => d.needs_review && !d.reviewed).length,
      }))
      .sort((a, b) => a.name.localeCompare(b.name))
  }, [docsByRepo])

  // Group documents by category for sidebar
  const docsByCategory = documents.reduce((acc, doc) => {
    if (!acc[doc.category]) acc[doc.category] = []
    acc[doc.category].push(doc)
    return acc
  }, {} as Record<DocumentCategory, DocumentListItem[]>)

  // Filter documents
  const filteredDocs = documents.filter((doc) => {
    // Filter by mode
    if (filterMode === 'manual' && doc.source_repo_id) return false
    if (filterMode === 'auto-generated' && !doc.source_repo_id) return false

    // Filter by repo
    if (selectedRepoId && doc.source_repo_id !== selectedRepoId) return false

    // Filter by category
    if (selectedCategory && doc.category !== selectedCategory) return false

    // Filter by review status
    if (reviewFilter === 'needs-review' && !(doc.needs_review && !doc.reviewed)) return false
    if (reviewFilter === 'reviewed' && !doc.reviewed) return false
    if (reviewFilter === 'user-edited' && !doc.user_edited) return false

    // Search filter
    if (search) {
      const searchLower = search.toLowerCase()
      return (
        doc.title.toLowerCase().includes(searchLower) ||
        doc.description?.toLowerCase().includes(searchLower) ||
        doc.tags.some((t) => t.toLowerCase().includes(searchLower)) ||
        doc.source_repo?.name.toLowerCase().includes(searchLower)
      )
    }
    return true
  })

  const updateUrlParams = (updates: { category?: string | null; search?: string; repo?: string | null }) => {
    const params = new URLSearchParams()
    const category = updates.category !== undefined ? updates.category : selectedCategory
    const searchVal = updates.search !== undefined ? updates.search : search
    const repo = updates.repo !== undefined ? updates.repo : selectedRepoId

    if (category) params.set('category', category)
    if (searchVal) params.set('search', searchVal)
    if (repo) params.set('repo', repo)

    router.push(`/projects/${projectId}/documents${params.toString() ? `?${params.toString()}` : ''}`)
  }

  const handleCategoryClick = (category: DocumentCategory | null) => {
    setSelectedCategory(category)
    setSelectedRepoId(null)
    setFilterMode('all')
    updateUrlParams({ category, repo: null })
  }

  const handleSearch = (value: string) => {
    setSearch(value)
    updateUrlParams({ search: value })
  }

  const handleFilterModeClick = (mode: FilterMode) => {
    setFilterMode(mode)
    setSelectedCategory(null)
    setSelectedRepoId(null)
    updateUrlParams({ category: null, repo: null })
  }

  const handleRepoClick = (repoId: string) => {
    setSelectedRepoId(repoId)
    setSelectedCategory(null)
    setFilterMode('auto-generated')
    setReviewFilter('all')
    updateUrlParams({ category: null, repo: repoId })
  }

  const handleReviewFilterClick = (filter: ReviewFilter) => {
    setReviewFilter(filter)
    // Don't clear other filters - review filter works as an overlay
  }

  const toggleRepoExpanded = (repoId: string) => {
    const newExpanded = new Set(expandedRepos)
    if (newExpanded.has(repoId)) {
      newExpanded.delete(repoId)
    } else {
      newExpanded.add(repoId)
    }
    setExpandedRepos(newExpanded)
  }

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections)
    if (newExpanded.has(section)) {
      newExpanded.delete(section)
    } else {
      newExpanded.add(section)
    }
    setExpandedSections(newExpanded)
  }

  const clearAllFilters = () => {
    setFilterMode('all')
    setSelectedCategory(null)
    setSelectedRepoId(null)
    setReviewFilter('all')
    updateUrlParams({ category: null, repo: null })
  }

  const toggleSelection = (id: string) => {
    const newSelected = new Set(selectedIds)
    if (newSelected.has(id)) {
      newSelected.delete(id)
    } else {
      newSelected.add(id)
    }
    setSelectedIds(newSelected)
  }

  const selectAll = () => {
    setSelectedIds(new Set(filteredDocs.map(d => d.id)))
  }

  const clearSelection = () => {
    setSelectedIds(new Set())
    setSelectionMode(false)
  }

  const handleBulkDelete = async () => {
    if (selectedIds.size === 0) return

    setIsDeleting(true)
    try {
      const response = await fetch(`/api/projects/${projectId}/documents`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ids: Array.from(selectedIds) }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || 'Failed to delete documents')
      }

      toast({
        title: 'Documents Deleted',
        description: `Successfully deleted ${data.deleted} document${data.deleted !== 1 ? 's' : ''}.`,
      })

      setSelectedIds(new Set())
      setSelectionMode(false)
      setShowDeleteDialog(false)
      router.refresh()
    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to delete documents',
        variant: 'destructive',
      })
    } finally {
      setIsDeleting(false)
    }
  }

  const hasActiveFilters = filterMode !== 'all' || selectedCategory || selectedRepoId || reviewFilter !== 'all'

  return (
    <div className="flex h-[calc(100vh-10rem)]">
      {/* Sidebar */}
      <div className="w-72 flex-shrink-0 border-r pr-4 space-y-1 overflow-y-auto">
        {/* All Documents - Always visible at top */}
        <button
          onClick={clearAllFilters}
          className={cn(
            'w-full flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-md transition-colors',
            !hasActiveFilters
              ? 'bg-primary text-primary-foreground'
              : 'hover:bg-muted'
          )}
        >
          <FileText className="h-4 w-4" />
          All Documents
          <span className="ml-auto text-xs opacity-70">{documents.length}</span>
        </button>

        <div className="h-px bg-border my-2" />

        {/* Quick Filters Section */}
        <Collapsible open={expandedSections.has('quick-filters')} onOpenChange={() => toggleSection('quick-filters')}>
          <CollapsibleTrigger className="w-full flex items-center justify-between px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground hover:text-foreground">
            <span>Review Status</span>
            <ChevronDown className={cn(
              'h-3 w-3 transition-transform',
              !expandedSections.has('quick-filters') && '-rotate-90'
            )} />
          </CollapsibleTrigger>
          <CollapsibleContent className="space-y-0.5 pt-1">
            <button
              onClick={() => handleReviewFilterClick('needs-review')}
              className={cn(
                'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                reviewFilter === 'needs-review'
                  ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400'
                  : 'hover:bg-muted'
              )}
            >
              <AlertCircle className="h-4 w-4 text-yellow-600" />
              Needs Review
              {reviewCounts.needsReview > 0 && (
                <Badge variant="secondary" className="ml-auto h-5 px-1.5 text-xs bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-500">
                  {reviewCounts.needsReview}
                </Badge>
              )}
            </button>

            <button
              onClick={() => handleReviewFilterClick('reviewed')}
              className={cn(
                'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                reviewFilter === 'reviewed'
                  ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400'
                  : 'hover:bg-muted'
              )}
            >
              <CheckCircle2 className="h-4 w-4 text-green-600" />
              Reviewed
              <span className="ml-auto text-xs opacity-70">{reviewCounts.reviewed}</span>
            </button>

            <button
              onClick={() => handleReviewFilterClick('user-edited')}
              className={cn(
                'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                reviewFilter === 'user-edited'
                  ? 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400'
                  : 'hover:bg-muted'
              )}
            >
              <Pencil className="h-4 w-4 text-blue-600" />
              User Edited
              <span className="ml-auto text-xs opacity-70">{reviewCounts.userEdited}</span>
            </button>

            {reviewFilter !== 'all' && (
              <button
                onClick={() => setReviewFilter('all')}
                className="w-full flex items-center gap-2 px-3 py-1 text-xs text-muted-foreground hover:text-foreground"
              >
                <X className="h-3 w-3" />
                Clear review filter
              </button>
            )}
          </CollapsibleContent>
        </Collapsible>

        <div className="h-px bg-border my-2" />

        {/* Source Section */}
        <Collapsible open={expandedSections.has('source')} onOpenChange={() => toggleSection('source')}>
          <CollapsibleTrigger className="w-full flex items-center justify-between px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground hover:text-foreground">
            <span>Source</span>
            <ChevronDown className={cn(
              'h-3 w-3 transition-transform',
              !expandedSections.has('source') && '-rotate-90'
            )} />
          </CollapsibleTrigger>
          <CollapsibleContent className="space-y-0.5 pt-1">
            <button
              onClick={() => handleFilterModeClick('manual')}
              className={cn(
                'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                filterMode === 'manual'
                  ? 'bg-primary text-primary-foreground'
                  : 'hover:bg-muted'
              )}
            >
              <Pencil className="h-4 w-4" />
              Manual
              <span className="ml-auto text-xs opacity-70">{manualDocs.length}</span>
            </button>

            <button
              onClick={() => handleFilterModeClick('auto-generated')}
              className={cn(
                'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                filterMode === 'auto-generated' && !selectedRepoId
                  ? 'bg-primary text-primary-foreground'
                  : 'hover:bg-muted'
              )}
            >
              <Bot className="h-4 w-4" />
              Auto-Generated
              <span className="ml-auto text-xs opacity-70">{autoGeneratedDocs.length}</span>
            </button>
          </CollapsibleContent>
        </Collapsible>

        <div className="h-px bg-border my-2" />

        {/* Repositories Section */}
        <Collapsible open={expandedSections.has('repositories')} onOpenChange={() => toggleSection('repositories')}>
          <CollapsibleTrigger className="w-full flex items-center justify-between px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground hover:text-foreground">
            <span>Repositories</span>
            <ChevronDown className={cn(
              'h-3 w-3 transition-transform',
              !expandedSections.has('repositories') && '-rotate-90'
            )} />
          </CollapsibleTrigger>
          <CollapsibleContent className="space-y-0.5 pt-1">
            {repoList.length > 0 ? (
              repoList.map((repo) => {
                const isExpanded = expandedRepos.has(repo.id)
                const repoDocs = docsByRepo[repo.id]?.docs || []

                return (
                  <div key={repo.id}>
                    <button
                      onClick={() => handleRepoClick(repo.id)}
                      className={cn(
                        'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                        selectedRepoId === repo.id
                          ? 'bg-primary text-primary-foreground'
                          : 'hover:bg-muted'
                      )}
                    >
                      <FolderGit2 className="h-4 w-4" />
                      <span className="truncate flex-1 text-left">{repo.name}</span>
                      <span className="flex items-center gap-1.5">
                        {repo.needsReviewCount > 0 && (
                          <Badge variant="secondary" className="h-4 px-1 text-[10px] bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-500">
                            {repo.needsReviewCount}
                          </Badge>
                        )}
                        <span className="text-xs opacity-70">{repo.count}</span>
                        <ChevronRight
                          className={cn(
                            'h-3 w-3 transition-transform',
                            isExpanded && 'rotate-90'
                          )}
                          onClick={(e) => {
                            e.stopPropagation()
                            toggleRepoExpanded(repo.id)
                          }}
                        />
                      </span>
                    </button>

                    {isExpanded && selectedRepoId === repo.id && (
                      <div className="ml-6 mt-0.5 space-y-0.5 border-l pl-2">
                        {repoDocs.map((doc) => (
                          <Link
                            key={doc.id}
                            href={`/projects/${projectId}/documents/${doc.id}`}
                            className={cn(
                              'flex items-center gap-1.5 px-2 py-1 text-xs rounded transition-colors hover:bg-muted',
                              doc.needs_review && !doc.reviewed && 'text-yellow-600 dark:text-yellow-500'
                            )}
                          >
                            {doc.reviewed ? (
                              <CheckCircle2 className="h-3 w-3 text-green-600 flex-shrink-0" />
                            ) : doc.needs_review ? (
                              <AlertCircle className="h-3 w-3 text-yellow-600 flex-shrink-0" />
                            ) : (
                              <FileText className="h-3 w-3 flex-shrink-0" />
                            )}
                            <span className="truncate">
                              {doc.title.replace(`${repo.name}/`, '')}
                            </span>
                          </Link>
                        ))}
                      </div>
                    )}
                  </div>
                )
              })
            ) : (
              <p className="text-xs text-muted-foreground px-3 py-2">
                No repositories with docs yet. Generate docs from the Repos page.
              </p>
            )}
          </CollapsibleContent>
        </Collapsible>

        <div className="h-px bg-border my-2" />

        {/* Categories Section */}
        <Collapsible open={expandedSections.has('categories')} onOpenChange={() => toggleSection('categories')}>
          <CollapsibleTrigger className="w-full flex items-center justify-between px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground hover:text-foreground">
            <span>Categories</span>
            <ChevronDown className={cn(
              'h-3 w-3 transition-transform',
              !expandedSections.has('categories') && '-rotate-90'
            )} />
          </CollapsibleTrigger>
          <CollapsibleContent className="space-y-0.5 pt-1">
            {(Object.keys(DOCUMENT_CATEGORY_LABELS) as DocumentCategory[]).map((category) => {
              const Icon = CATEGORY_ICONS[category]
              const count = docsByCategory[category]?.length || 0

              return (
                <button
                  key={category}
                  onClick={() => handleCategoryClick(category)}
                  className={cn(
                    'w-full flex items-center gap-2 px-3 py-1.5 text-sm rounded-md transition-colors',
                    selectedCategory === category
                      ? 'bg-primary text-primary-foreground'
                      : 'hover:bg-muted',
                    count === 0 && 'opacity-50'
                  )}
                  disabled={count === 0}
                >
                  <Icon className="h-4 w-4" />
                  <span className="truncate">{DOCUMENT_CATEGORY_LABELS[category]}</span>
                  <span className="ml-auto text-xs opacity-70">{count}</span>
                </button>
              )
            })}
          </CollapsibleContent>
        </Collapsible>
      </div>

      {/* Main content */}
      <div className="flex-1 pl-6 overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <FileText className="h-6 w-6" />
              Documentation
            </h1>
            <p className="text-muted-foreground">
              {(() => {
                const parts: string[] = []

                // Source filter
                if (selectedRepoId && docsByRepo[selectedRepoId]) {
                  parts.push(docsByRepo[selectedRepoId].repo.name)
                } else if (filterMode === 'manual') {
                  parts.push('Manual')
                } else if (filterMode === 'auto-generated') {
                  parts.push('Auto-generated')
                }

                // Review filter
                if (reviewFilter === 'needs-review') {
                  parts.push('needs review')
                } else if (reviewFilter === 'reviewed') {
                  parts.push('reviewed')
                } else if (reviewFilter === 'user-edited') {
                  parts.push('user edited')
                }

                // Category filter
                if (selectedCategory) {
                  parts.push(DOCUMENT_CATEGORY_LABELS[selectedCategory].toLowerCase())
                }

                if (parts.length === 0) {
                  return `All documents for ${projectName}`
                }
                return `${parts.join(' · ')} documents for ${projectName}`
              })()}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {canDelete && documents.length > 0 && (
              selectionMode ? (
                <>
                  <Button variant="ghost" size="sm" onClick={selectAll}>
                    <CheckSquare className="h-4 w-4 mr-2" />
                    Select All ({filteredDocs.length})
                  </Button>
                  <Button variant="ghost" size="sm" onClick={clearSelection}>
                    <X className="h-4 w-4 mr-2" />
                    Cancel
                  </Button>
                  {selectedIds.size > 0 && (
                    <Button
                      variant="destructive"
                      size="sm"
                      onClick={() => setShowDeleteDialog(true)}
                    >
                      <Trash2 className="h-4 w-4 mr-2" />
                      Delete ({selectedIds.size})
                    </Button>
                  )}
                </>
              ) : (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSelectionMode(true)}
                >
                  <CheckSquare className="h-4 w-4 mr-2" />
                  Select
                </Button>
              )
            )}
            <Link href={`/projects/${projectId}/documents/new`}>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                New Document
              </Button>
            </Link>
          </div>
        </div>

        {/* Search and Active Filters */}
        <div className="space-y-3 mb-6">
          <div className="flex gap-2">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search documents..."
                value={search}
                onChange={(e) => handleSearch(e.target.value)}
                className="pl-9"
              />
            </div>
          </div>

          {/* Active Filters Display */}
          {hasActiveFilters && (
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs text-muted-foreground">Active filters:</span>

              {filterMode === 'manual' && (
                <Badge variant="secondary" className="gap-1">
                  <Pencil className="h-3 w-3" />
                  Manual
                  <button onClick={() => handleFilterModeClick('all')} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              {filterMode === 'auto-generated' && !selectedRepoId && (
                <Badge variant="secondary" className="gap-1">
                  <Bot className="h-3 w-3" />
                  Auto-Generated
                  <button onClick={() => handleFilterModeClick('all')} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              {selectedRepoId && docsByRepo[selectedRepoId] && (
                <Badge variant="secondary" className="gap-1">
                  <FolderGit2 className="h-3 w-3" />
                  {docsByRepo[selectedRepoId].repo.name}
                  <button onClick={() => { setSelectedRepoId(null); setFilterMode('all'); updateUrlParams({ repo: null }) }} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              {reviewFilter === 'needs-review' && (
                <Badge variant="secondary" className="gap-1 bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400">
                  <AlertCircle className="h-3 w-3" />
                  Needs Review
                  <button onClick={() => setReviewFilter('all')} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              {reviewFilter === 'reviewed' && (
                <Badge variant="secondary" className="gap-1 bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">
                  <CheckCircle2 className="h-3 w-3" />
                  Reviewed
                  <button onClick={() => setReviewFilter('all')} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              {reviewFilter === 'user-edited' && (
                <Badge variant="secondary" className="gap-1 bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
                  <Pencil className="h-3 w-3" />
                  User Edited
                  <button onClick={() => setReviewFilter('all')} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              {selectedCategory && (
                <Badge variant="secondary" className="gap-1">
                  {(() => { const Icon = CATEGORY_ICONS[selectedCategory]; return <Icon className="h-3 w-3" /> })()}
                  {DOCUMENT_CATEGORY_LABELS[selectedCategory]}
                  <button onClick={() => handleCategoryClick(null)} className="ml-1 hover:text-foreground">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              )}

              <Button
                variant="ghost"
                size="sm"
                onClick={clearAllFilters}
                className="h-6 text-xs"
              >
                Clear all
              </Button>
            </div>
          )}
        </div>

        {/* Document list */}
        {filteredDocs.length === 0 ? (
          <Card>
            <CardContent className="flex flex-col items-center justify-center py-12">
              <FileText className="h-12 w-12 text-muted-foreground mb-4" />
              <h3 className="text-lg font-semibold mb-2">No documents yet</h3>
              <p className="text-muted-foreground text-center max-w-sm mb-4">
                {search || selectedCategory
                  ? 'No documents match your search criteria.'
                  : 'Create your first document using the Document Builder.'}
              </p>
              <Link href={`/projects/${projectId}/documents/new`}>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  Create Document
                </Button>
              </Link>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-2">
            {filteredDocs.map((doc) => {
              const Icon = CATEGORY_ICONS[doc.category]
              const colorClass = CATEGORY_COLORS[doc.category]
              const isSelected = selectedIds.has(doc.id)

              const cardContent = (
                <Card className={cn(
                  "hover:border-primary/50 transition-colors cursor-pointer",
                  isSelected && "border-primary bg-primary/5"
                )}>
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex items-start gap-3 min-w-0">
                        {selectionMode && (
                          <Checkbox
                            checked={isSelected}
                            onCheckedChange={() => toggleSelection(doc.id)}
                            className="mt-1"
                            onClick={(e) => e.stopPropagation()}
                          />
                        )}
                        <div
                          className={cn(
                            'flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center',
                            colorClass
                          )}
                        >
                          <Icon className="h-5 w-5" />
                        </div>
                        <div className="min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <h3 className="font-medium truncate">{doc.title}</h3>
                            <Badge variant="secondary" className="text-xs">
                              {DOCUMENT_CATEGORY_LABELS[doc.category]}
                            </Badge>
                            {/* Review Status Badges for auto-generated docs */}
                            {doc.source_repo_id && (
                              <>
                                <Badge
                                  variant="outline"
                                  className="text-xs bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/30 dark:text-purple-400 dark:border-purple-800"
                                >
                                  <Bot className="h-3 w-3 mr-1" />
                                  Auto-generated
                                </Badge>
                                {doc.needs_review && !doc.reviewed && (
                                  <Badge
                                    variant="outline"
                                    className="text-xs bg-yellow-50 text-yellow-700 border-yellow-200 dark:bg-yellow-950/30 dark:text-yellow-400 dark:border-yellow-800"
                                  >
                                    <AlertCircle className="h-3 w-3 mr-1" />
                                    Needs Review
                                  </Badge>
                                )}
                                {doc.reviewed && (
                                  <Badge
                                    variant="outline"
                                    className="text-xs bg-green-50 text-green-700 border-green-200 dark:bg-green-950/30 dark:text-green-400 dark:border-green-800"
                                  >
                                    <CheckCircle2 className="h-3 w-3 mr-1" />
                                    Reviewed
                                  </Badge>
                                )}
                                {doc.user_edited && (
                                  <Badge
                                    variant="outline"
                                    className="text-xs bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950/30 dark:text-blue-400 dark:border-blue-800"
                                  >
                                    <Pencil className="h-3 w-3 mr-1" />
                                    Edited
                                  </Badge>
                                )}
                                {doc.verification_score !== undefined && doc.verification_score > 0 && (
                                  <Badge
                                    variant="outline"
                                    className={cn(
                                      'text-xs',
                                      doc.verification_score >= 80
                                        ? 'bg-green-50 text-green-700 border-green-200 dark:bg-green-950/30 dark:text-green-400'
                                        : doc.verification_score >= 50
                                        ? 'bg-yellow-50 text-yellow-700 border-yellow-200 dark:bg-yellow-950/30 dark:text-yellow-400'
                                        : 'bg-red-50 text-red-700 border-red-200 dark:bg-red-950/30 dark:text-red-400'
                                    )}
                                  >
                                    Score: {doc.verification_score}%
                                  </Badge>
                                )}
                              </>
                            )}
                          </div>
                          {doc.description && (
                            <p className="text-sm text-muted-foreground line-clamp-1 mt-0.5">
                              {doc.description}
                            </p>
                          )}
                          <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
                            <span>
                              Updated {formatRelativeTime(doc.updated_at)}
                            </span>
                            {doc.creator && (
                              <>
                                <span>•</span>
                                <span>
                                  by {doc.creator.full_name || doc.creator.email}
                                </span>
                              </>
                            )}
                            {doc.source_repo && (
                              <>
                                <span>•</span>
                                <span className="flex items-center gap-1">
                                  <FolderGit2 className="h-3 w-3" />
                                  {doc.source_repo.name}
                                </span>
                              </>
                            )}
                          </div>
                          {doc.tags.length > 0 && (
                            <div className="flex gap-1 mt-2">
                              {doc.tags.slice(0, 3).map((tag) => (
                                <Badge key={tag} variant="outline" className="text-xs">
                                  {tag}
                                </Badge>
                              ))}
                              {doc.tags.length > 3 && (
                                <span className="text-xs text-muted-foreground">
                                  +{doc.tags.length - 3}
                                </span>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                      <ChevronRight className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                    </div>
                  </CardContent>
                </Card>
              )

              if (selectionMode) {
                return (
                  <div
                    key={doc.id}
                    onClick={() => toggleSelection(doc.id)}
                    className="block"
                  >
                    {cardContent}
                  </div>
                )
              }

              return (
                <Link
                  key={doc.id}
                  href={`/projects/${projectId}/documents/${doc.id}`}
                  className="block"
                >
                  {cardContent}
                </Link>
              )
            })}
          </div>
        )}
      </div>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete {selectedIds.size} Document{selectedIds.size !== 1 ? 's' : ''}?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone. The selected document{selectedIds.size !== 1 ? 's' : ''} will be permanently deleted.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isDeleting}>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleBulkDelete}
              disabled={isDeleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting ? 'Deleting...' : 'Delete'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
